Media Temporary Upload implementation
weapnl/laravel-junction pull request #37
Opened 2024-08-30 07:30 UTC by jobjen02

2024-09-04 14:00 UTC, JurianVW requested changes

2024-09-04 14:00 UTC, JurianVW commented on config/junction.php
> +    ],
Might be useful to add some comments/docks like usual is in a config to give explanation about what it does.

2024-09-04 14:00 UTC, JurianVW commented on database/migrations/2024_08_29_124400_create_media_temporary_uploads_table.php
> +            $table->foreignId('created_by_user_id')->index()->constrained(app(config('auth.providers.users.model'))->tableName())->cascadeOnDelete();
`->tableName()` is not available on the User model by default. So you need to use the method available by laravel, which is `->getTable()`

2024-09-04 14:00 UTC, JurianVW commented on src/Http/Controllers/Requests/DefaultFormRequest.php
> +                    abort_if(Auth::user()->id !== $media->model->created_by_user_id, 404);
- Might be bit cleaner to use `Auth::id()`
- Should this be `403` because it seems more like an authorization issue?

2024-09-04 14:00 UTC, JurianVW commented on src/Http/Controllers/Traits/HasMedia.php
> +                    if ($collectionSizeLimit = optional($model->getMediaCollection($media->collection_name))->collectionSizeLimit) {
Could be simplified a bit by doing `if ($collectionSizeLimit = $model->getMediaCollection($media->collection_name)?->collectionSizeLimit) {`? Or is that different?

2024-09-04 14:00 UTC, JurianVW commented on src/Http/Controllers/Traits/HasMedia.php
> +                    $media->save();
Did you look at this? maybe this automatically handles the single-file collections? https://spatie.be/docs/laravel-medialibrary/v11/advanced-usage/moving-media

2024-09-04 14:00 UTC, JurianVW commented on src/Http/Controllers/Traits/HasMedia.php
> +                    abort_if($media->model_type !== MediaTemporaryUpload::class || Auth::user()->id !== $media->model->created_by_user_id, 404);
- Might be bit cleaner to use Auth::id()
- Should this be 403 because it seems more like an authorization issue?

2024-09-05 06:45 UTC, jobjen02 commented on src/JunctionServiceProvider.php
> +        if (class_exists(Media::class)) {
This is slower (avg 10ms) then the class_exists, as discussed, we will use the class_exists method.

2024-09-05 09:19 UTC, JurianVW commented on src/Http/Controllers/Requests/DefaultFormRequest.php
> +    protected function prepareForValidation()
Can you add return type?

2024-09-05 09:45 UTC, JurianVW approved these changes

2024-09-05 09:47 UTC, merged